//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated using  OData2Poco System.
//     Service Url: https://farbank-test.sandbox.operations.dynamics.com/data
//     MetaData Version: 4.0
//     Generated On: 2022-05-05T10:46:57
// </auto-generated>
//------------------------------------------------------------------------------
//

using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Farbank.Pattern.Nester.SageSpecs.Server.Models
{
	public partial class FBEProdJournalRoute
	{
	    [Key]
	    [Required]
	    public string dataAreaId {get;set;} //PrimaryKey not null

	    [Key]
	    [Required]
	    public string JournalId {get;set;} //PrimaryKey not null

	    [Key]
	    [Required]
	    public decimal LineNum {get;set;} //PrimaryKey not null

	    [Required]
	    public int OprNum {get;set;} // not null

	    [Required]
	    public int ToTime {get;set;} // not null

	    public string CategoryQtyId {get;set;} 

	    public string FBEWorker {get;set;} 

	    public NoYes ProdReportFinished {get;set;} 

	    public string ProdId {get;set;} 

	    public string SageBlankBatchId {get;set;} 

	    public string OprId {get;set;} 

	    [Required]
	    public decimal ExecutedPct {get;set;} // not null

	    [Required]
	    public decimal HourPrice {get;set;} // not null

	    public string JobId {get;set;} 

	    public string ProdInventDimId {get;set;} 

	    public string FBEPreviousJournalId {get;set;} 

	    public string SageBlankCoater {get;set;} 

	    [Required]
	    public decimal PdsCWQtyError {get;set;} // not null

	    [Required]
	    public decimal QtyGood {get;set;} // not null

	    [Required]
	    public DateTimeOffset TransDate {get;set;} // not null

	    public NoYes OprFinished {get;set;} 

	    [Required]
	    public int SageDrumNumber {get;set;} // not null

	    [Required]
	    public decimal QtyPrice {get;set;} // not null

	    public string ProdPickListJournalId {get;set;} 

	    public string SageBlankColorCoat {get;set;} 

	    [Required]
	    public int FromTime {get;set;} // not null

	    public string SageRodCoater {get;set;} 

	    public string SageDefectCode {get;set;} 

	    public string CategoryHoursId {get;set;} 

	    public RouteOprPriority OprPriority {get;set;} 

	    public RouteJobType JobType {get;set;} 

	    [Required]
	    public decimal PdsCWQtyGood {get;set;} // not null

	    public string SageCompleteCode {get;set;} 

	    public string Voucher {get;set;} 

	    public string SageBlankClearCoat {get;set;} 

	    public NoYes Cancelled {get;set;} 

	    [Required]
	    public decimal QtyError {get;set;} // not null

	    public string SageReworkQty {get;set;} 

	    public NoYes JobFinished {get;set;} 

	    public ProdErrorCause ErrorCause {get;set;} 

	    public string WrkCtrId {get;set;} 

	    [Required]
	    public decimal Hours {get;set;} // not null

	    public string DefaultDimensionDisplayValue {get;set;} 

	    public NoYes ProdPickList {get;set;} 

	    public string ProdReportFinishedJournalId {get;set;} 

	}

	public partial class ProductionOrderRouteOperation
	{
	    [Key]
	    [Required]
	    public string dataAreaId {get;set;} //PrimaryKey not null

	    [Key]
	    [Required]
	    public string ProductionOrderNumber {get;set;} //PrimaryKey not null

	    [Key]
	    [Required]
	    public int OperationNumber {get;set;} //PrimaryKey not null

	    [Key]
	    public RouteOprPriority OperationPriority {get;set;} //PrimaryKey

	    [Required]
	    public int ScheduledFromTime {get;set;} // not null

	    [Required]
	    public decimal ProcessQuantity {get;set;} // not null

	    public string QuantityCostCategoryId {get;set;} 

	    [Required]
	    public decimal EstimatedProcessTime {get;set;} // not null

	    public string SetupProductionJobId {get;set;} 

	    [Required]
	    public int NextOperationNumber {get;set;} // not null

	    public SchedJobLinkType NextOperationLinkType {get;set;} 

	    public string RouteGroupId {get;set;} 

	    [Required]
	    public decimal LoadPercentage {get;set;} // not null

	    [Required]
	    public int ResourceQuantity {get;set;} // not null

	    public string ProcessProductionJobId {get;set;} 

	    [Required]
	    public int ScheduledEndTime {get;set;} // not null

	    [Required]
	    public DateTimeOffset ScheduledFromDate {get;set;} // not null

	    [Required]
	    public decimal OperationsTimeToHourConversionFactor {get;set;} // not null

	    [Required]
	    public decimal SetupTime {get;set;} // not null

	    [Required]
	    public int RouteOperationSequence {get;set;} // not null

	    [Required]
	    public decimal OverlapOperationQuantity {get;set;} // not null

	    [Required]
	    public decimal SetupCompletionPercentage {get;set;} // not null

	    [Required]
	    public decimal EstimatedSetupTime {get;set;} // not null

	    [Required]
	    public DateTimeOffset ScheduledEndDate {get;set;} // not null

	    [Required]
	    public decimal QueueTimeBefore {get;set;} // not null

	    [Required]
	    public decimal EstimatedOperationQuantity {get;set;} // not null

	    public NoYes IsConstantConsumptionReleased {get;set;} 

	    public NoYes IsOperationStarted {get;set;} 

	    [Required]
	    public decimal ProcessCompletionPercentage {get;set;} // not null

	    public string CostingOperationResourceId {get;set;} 

	    public string WorkingTimeSchedulingPropertyId {get;set;} 

	    [Required]
	    public decimal ScrapPercentage {get;set;} // not null

	    [Required]
	    public decimal AccumulatedScrapPercentage {get;set;} // not null

	    [Required]
	    public decimal QueueTimeAfter {get;set;} // not null

	    public string OperationId {get;set;} 

	    public string DefaultLedgerDimensionDisplayValue {get;set;} 

	    [Required]
	    public decimal ProcessTime {get;set;} // not null

	    public NoYes IsOperationCompleted {get;set;} 

	    public string SetupCostCategoryId {get;set;} 

	    [Required]
	    public decimal TransferBatchQuantity {get;set;} // not null

	    public RouteOprType RouteType {get;set;} 

	    public JmgJobPayTypeEnum RouteOperationRateMethod {get;set;} 

	    [Required]
	    public decimal TransitTime {get;set;} // not null

	    public string ProcessCostCategoryId {get;set;} 

	    public ProdBackStatus RouteOperationRemainderStatus {get;set;} 

	}

	public partial class ProductBarcode
	{
	    [Key]
	    [Required]
	    public string dataAreaId {get;set;} //PrimaryKey not null

	    [Key]
	    [Required]
	    public string ItemNumber {get;set;} //PrimaryKey not null

	    [Key]
	    [Required]
	    public string ProductConfigurationId {get;set;} //PrimaryKey not null

	    [Key]
	    [Required]
	    public string ProductColorId {get;set;} //PrimaryKey not null

	    [Key]
	    [Required]
	    public string ProductSizeId {get;set;} //PrimaryKey not null

	    [Key]
	    [Required]
	    public string ProductStyleId {get;set;} //PrimaryKey not null

	    [Key]
	    [Required]
	    public string ProductQuantityUnitSymbol {get;set;} //PrimaryKey not null

	    [Key]
	    [Required]
	    public string BarcodeSetupId {get;set;} //PrimaryKey not null

	    [Key]
	    [Required]
	    public string Barcode {get;set;} //PrimaryKey not null

	    public string ProductDescription {get;set;} 

	    public NoYes IsDefaultScannedBarcode {get;set;} 

	    public NoYes IsDefaultDisplayedBarcode {get;set;} 

	    public NoYes IsDefaultPrintedBarcode {get;set;} 

	    [Required]
	    public decimal ProductQuantity {get;set;} // not null

	}

	public partial class ProductionOrderHeader
	{
	    [Key]
	    [Required]
	    public string dataAreaId {get;set;} //PrimaryKey not null

	    [Key]
	    [Required]
	    public string ProductionOrderNumber {get;set;} //PrimaryKey not null

	    public string ProductionOrderName {get;set;} 

	    [Required]
	    public DateTimeOffset ScheduledEndDate {get;set;} // not null

	    [Required]
	    public decimal ProductionConsumptionWidthConversionFactor {get;set;} // not null

	    public string ProductStyleId {get;set;} 

	    public string SubcontractingPurchaseOrderNumber {get;set;} 

	    public NoYes SkipCreateProductionBOMLines {get;set;} 

	    public string ProductionGroupId {get;set;} 

	    [Required]
	    public int DeliveryTime {get;set;} // not null

	    public ProdStatus ProductionOrderStatus {get;set;} 

	    public ProdReservation AutoReservationMode {get;set;} 

	    public string DemandProductionOrderLineInventoryLotId {get;set;} 

	    [Required]
	    public DateTimeOffset EndedDate {get;set;} // not null

	    [Required]
	    public DateTimeOffset SourceBOMVersionValidityDate {get;set;} // not null

	    public ProdBackStatus ProductionOrderRemainderStatus {get;set;} 

	    [Required]
	    public int ProductionOrderPriority {get;set;} // not null

	    public string DemandProductionOrderNumber {get;set;} 

	    public string InventoryStatusId {get;set;} 

	    public string ItemNumber {get;set;} 

	    [Required]
	    public DateTimeOffset ReportedAsFinishedDate {get;set;} // not null

	    public string ProductionWarehouseId {get;set;} 

	    public string ProductionSiteId {get;set;} 

	    public string ProductSerialNumber {get;set;} 

	    [Required]
	    public DateTimeOffset ScheduledDate {get;set;} // not null

	    public string DemandTransferOrderNumber {get;set;} 

	    public string ProductSizeId {get;set;} 

	    public string DemandSalesOrderNumber {get;set;} 

	    [Required]
	    public decimal ProductionConsumptionDensityConversionFactor {get;set;} // not null

	    public string DemandProductionOrderLineNumber {get;set;} 

	    public string SubcontractingPurchaseOrderLineInventoryLotId {get;set;} 

	    [Required]
	    public DateTimeOffset StartedDate {get;set;} // not null

	    public string DemandProductionOrderHeaderInventoryLotId {get;set;} 

	    public ProdSchedStatus SchedulingMethod {get;set;} 

	    [Required]
	    public DateTimeOffset ScheduledStartDate {get;set;} // not null

	    public string DemandInventoryJournalLineInventoryLotId {get;set;} 

	    [Required]
	    public decimal ScheduledQuantity {get;set;} // not null

	    [Required]
	    public DateTimeOffset EstimatedDate {get;set;} // not null

	    public string WorkingTimeSchedulingPropertyId {get;set;} 

	    [Required]
	    public DateTimeOffset ReleasedDate {get;set;} // not null

	    public string InventoryLotId {get;set;} 

	    [Required]
	    public decimal ProductionConsumptionHeightConversionFactor {get;set;} // not null

	    public string SourcePlannedOrderNumber {get;set;} 

	    public string ProductConfigurationId {get;set;} 

	    [Required]
	    public DateTimeOffset LastSchedulingDate {get;set;} // not null

	    [Required]
	    public decimal StartedQuantity {get;set;} // not null

	    public string ProductionPoolId {get;set;} 

	    public string LicensePlateNumber {get;set;} 

	    public string ParentProductionOrderNumber {get;set;} 

	    public string DemandTransferOrderLineReceivingInventoryLotId {get;set;} 

	    [Required]
	    public decimal PlanningPriority {get;set;} // not null

	    [Required]
	    public int LastSchedulingTime {get;set;} // not null

	    public string ProductVersionId {get;set;} 

	    [Required]
	    public decimal EstimatedQuantity {get;set;} // not null

	    public string SourceBOMId {get;set;} 

	    public string ProductionWarehouseLocationId {get;set;} 

	    public string DemandSalesOrderLineInventoryLotId {get;set;} 

	    public NoYes IsProductionOrderSchedulingLocked {get;set;} 

	    public ProdPostingType ProductionOrderLedgerPostingRule {get;set;} 

	    public string SourceMasterPlanId {get;set;} 

	    public CostProfitSet ProductionOrderProfitSettingMethod {get;set;} 

	    public SchedDirection LastSchedulingDateDirection {get;set;} 

	    public string ItemBatchNumber {get;set;} 

	    public NoYes IsProductionRouteOperationValid {get;set;} 

	    public string ProductColorId {get;set;} 

	    [Required]
	    public decimal RemainingReportAsFinishedQuantity {get;set;} // not null

	    public NoYes AreRouteJobsGenerated {get;set;} 

	    public string SourceRouteId {get;set;} 

	    public ProdWHSReleasePolicy WarehouseReleaseReservationRequirementRule {get;set;} 

	    [Required]
	    public int ScheduledStartTime {get;set;} // not null

	    [Required]
	    public DateTimeOffset DeliveryDate {get;set;} // not null

	    [Required]
	    public int ScheduledEndTime {get;set;} // not null

	    [Required]
	    public int ProductionLevel {get;set;} // not null

	    public string DefaultLedgerDimensionDisplayValue {get;set;} 

	    [Required]
	    public int GanttChartColorNumber {get;set;} // not null

	    [Required]
	    public decimal ProductionConsumptionDepthConversionFactor {get;set;} // not null

	    public string DemandInventoryJournalNumber {get;set;} 

	    public NoYes SkipCreateProductionRouteOperations {get;set;} 

	    public string InventoryOwnerId {get;set;} 

	    public string RecordCreatedBy {get;set;} 

	    [Required]
	    public DateTimeOffset RecordCreatedDateTime {get;set;} // not null

	}

	public partial class FBEProdOrderRoute
	{
	    [Key]
	    [Required]
	    public string dataAreaId {get;set;} //PrimaryKey not null

	    [Key]
	    [Required]
	    public string ProdId {get;set;} //PrimaryKey not null

	    [Key]
	    [Required]
	    public int OprNum {get;set;} //PrimaryKey not null

	    [Key]
	    public RouteOprPriority OprPriority {get;set;} //PrimaryKey

	    [Required]
	    public decimal TranspTime {get;set;} // not null

	    [Required]
	    public decimal ProcessPerQty {get;set;} // not null

	    [Required]
	    public int ToTime {get;set;} // not null

	    public string JobIdSetup {get;set;} 

	    [Required]
	    public decimal OverlapQty {get;set;} // not null

	    public string OprId {get;set;} 

	    public NoYes OprStartedUp {get;set;} 

	    public string SetUpCategoryId {get;set;} 

	    public ProdBackStatus BackorderStatus {get;set;} 

	    public string JobId {get;set;} 

	    public string RouteGroupId {get;set;} 

	    public string ProcessCategoryId {get;set;} 

	    public RouteAll RouteOpr_RouteCode {get;set;} 

	    [Required]
	    public decimal CalcSetUp {get;set;} // not null

	    public string QtyCategoryId {get;set;} 

	    [Required]
	    public decimal CompletePct {get;set;} // not null

	    [Required]
	    public decimal FormulaFactor1 {get;set;} // not null

	    [Required]
	    public decimal SetupTime {get;set;} // not null

	    [Required]
	    public DateTimeOffset ToDate {get;set;} // not null

	    [Required]
	    public decimal ToHours {get;set;} // not null

	    [Required]
	    public decimal CalcProc {get;set;} // not null

	    public NoYes ConstantReleased {get;set;} 

	    public NoYes OprFinished {get;set;} 

	    [Required]
	    public decimal CalcQty {get;set;} // not null

	    [Required]
	    public decimal QueueTimeBefore {get;set;} // not null

	    [Required]
	    public int FromTime {get;set;} // not null

	    public string RouteOpr_OprId {get;set;} 

	    [Required]
	    public decimal ErrorPct {get;set;} // not null

	    public string PropertyId {get;set;} 

	    [Required]
	    public int OprNumNext {get;set;} // not null

	    public RouteFormula Formula {get;set;} 

	    public SchedJobLinkType LinkType {get;set;} 

	    public JmgJobPayTypeEnum JobPayType {get;set;} 

	    [Required]
	    public DateTimeOffset FromDate {get;set;} // not null

	    [Required]
	    public decimal AccError {get;set;} // not null

	    [Required]
	    public int Level {get;set;} // not null

	    public string RouteOpr_ItemRelation {get;set;} 

	    public string SiteId {get;set;} 

	    [Required]
	    public decimal TransferBatch {get;set;} // not null

	    public string RouteOpr_ConfigId {get;set;} 

	    public string RouteOpr_RouteRelation {get;set;} 

	    [Required]
	    public decimal QueueTimeAfter {get;set;} // not null

	    public string WrkCtrIdCost {get;set;} 

	    [Required]
	    public decimal ProcessTime {get;set;} // not null

	    public RouteOprType RouteType {get;set;} 

	    [Required]
	    public decimal ExecutedSetup {get;set;} // not null

	    public string DefaultDimensionDisplayValue {get;set;} 

	    public TableGroupAll RouteOpr_ItemCode {get;set;} 

	    [Required]
	    public decimal PhantomBOMFactor {get;set;} // not null

	    public NoYes SkipJobCreation {get;set;} 

	}

	public partial class SalesOrderHeaderV2
	{
	    [Key]
	    [Required]
	    public string dataAreaId {get;set;} //PrimaryKey not null

	    [Key]
	    [Required]
	    public string SalesOrderNumber {get;set;} //PrimaryKey not null

	    [Required]
	    public decimal OrderTotalChargesAmount {get;set;} // not null

	    public string FiscalDocumentOperationTypeId {get;set;} 

	    public string OrderTakerPersonnelNumber {get;set;} 

	    [Required]
	    public DateTimeOffset RequestedReceiptDate {get;set;} // not null

	    public string EInvoiceDimensionAccountCode {get;set;} 

	    public NoYes IsOwnEntryCertificateIssued {get;set;} 

	    public string InvoiceAddressStreet {get;set;} 

	    public string CampaignId {get;set;} 

	    public string FormattedDelveryAddress {get;set;} 

	    public string Email {get;set;} 

	    [Required]
	    public int BaseDocumentLineNumber {get;set;} // not null

	    public DocumentType_IT BaseDocumentType {get;set;} 

	    public string DefaultShippingSiteId {get;set;} 

	    public string TransportationBrokerId {get;set;} 

	    public string TransportationModeId {get;set;} 

	    public string DeliveryAddressDescription {get;set;} 

	    public string CFPSCode {get;set;} 

	    public NoYes IsInvoiceAddressPrivate {get;set;} 

	    public NoYes IsSalesProcessingStopped {get;set;} 

	    public string ShippingCarrierCustomerAccountNumber {get;set;} 

	    public string TMACustomerGroupId {get;set;} 

	    public string BankSpecificSymbol {get;set;} 

	    public SalesStatus SalesOrderStatus {get;set;} 

	    public string NumberSequenceGroupId {get;set;} 

	    public string SalesOrderOriginCode {get;set;} 

	    [Required]
	    public decimal InvoiceAddressLatitude {get;set;} // not null

	    public string CustomerPaymentFinancialInterestCode {get;set;} 

	    public string TransportationTemplateId {get;set;} 

	    public string InvoiceAddressStreetInKana {get;set;} 

	    public string BankConstantSymbol {get;set;} 

	    [Required]
	    public decimal OrderTotalTaxAmount {get;set;} // not null

	    public NoYes IsOneTimeCustomer {get;set;} 

	    public string SalesOrderPoolId {get;set;} 

	    public string DeliveryAddressCountryRegionId {get;set;} 

	    [Required]
	    public decimal DeliveryAddressLatitude {get;set;} // not null

	    public string TotalDiscountCustomerGroupCode {get;set;} 

	    public string DeliveryAddressCity {get;set;} 

	    public string SalesRebateCustomerGroupId {get;set;} 

	    public string ThirdPartySalesDigitalPlatformCNPJ {get;set;} 

	    public SalesDeliveryDateControlType SalesOrderPromisingMethod {get;set;} 

	    public string ProjectId {get;set;} 

	    public string ShippingCarrierId {get;set;} 

	    [Required]
	    public decimal TotalDiscountPercentage {get;set;} // not null

	    public string DeliveryAddressDistrictName {get;set;} 

	    public string DeliveryAddressCountyId {get;set;} 

	    [Required]
	    public DateTimeOffset ConfirmedReceiptDate {get;set;} // not null

	    public string BaseDocumentItemNumber {get;set;} 

	    public string DeliveryAddressZipCode {get;set;} 

	    public EFDocPresenceType_BR FiscalOperationPresenceType {get;set;} 

	    public string QuotationNumber {get;set;} 

	    public NoYes IsConsolidatedInvoiceTarget {get;set;} 

	    public string LanguageId {get;set;} 

	    public string DeliveryAddressDunsNumber {get;set;} 

	    public string MultilineDiscountCustomerGroupCode {get;set;} 

	    public string BaseDocumentNumber {get;set;} 

	    public string InvoiceAddressStateId {get;set;} 

	    public string ServiceFiscalInformationCode {get;set;} 

	    public string CustomerPaymentMethodSpecificationName {get;set;} 

	    public string CommissionCustomerGroupId {get;set;} 

	    public string DeliveryAddressName {get;set;} 

	    public string InvoiceAddressCountryRegionId {get;set;} 

	    [Required]
	    public DateTimeOffset PaymentTermsBaseDate {get;set;} // not null

	    public string DeliveryAddressStreetNumber {get;set;} 

	    public string CreditNoteReasonCode {get;set;} 

	    public string DeliveryAddressStreetInKana {get;set;} 

	    public string ChargeCustomerGroupId {get;set;} 

	    public string InvoiceAddressStreetNumber {get;set;} 

	    public NoYes IsDeliveryAddressPrivate {get;set;} 

	    public string TaxExemptNumber {get;set;} 

	    public NoYes AreTotalsCalculated {get;set;} 

	    [Required]
	    public decimal TotalDiscountAmount {get;set;} // not null

	    [Required]
	    public decimal OrderTotalAmount {get;set;} // not null

	    public string CustomersOrderReference {get;set;} 

	    public string FormattedInvoiceAddress {get;set;} 

	    public string OrderResponsiblePersonnelNumber {get;set;} 

	    public string ExportReason {get;set;} 

	    public string DeliveryAddressCountryRegionISOCode {get;set;} 

	    public string CashDiscountCode {get;set;} 

	    public string OrderOrAgreementCode {get;set;} 

	    public string PaymentScheduleName {get;set;} 

	    public string InvoiceAddressCountryRegionISOCode {get;set;} 

	    public string IntrastatTransactionCode {get;set;} 

	    public string URL {get;set;} 

	    [Required]
	    public decimal OrderTotalDiscountAmount {get;set;} // not null

	    public string CurrencyCode {get;set;} 

	    public InvoiceType_MY InvoiceType {get;set;} 

	    [Required]
	    public DateTimeOffset OrderCreationDateTime {get;set;} // not null

	    public NoYes ArePricesIncludingSalesTax {get;set;} 

	    public string InvoiceCustomerAccountNumber {get;set;} 

	    public string DeliveryAddressLocationId {get;set;} 

	    public string CommissionSalesRepresentativeGroupId {get;set;} 

	    public SettlementType CustomerTransactionSettlementType {get;set;} 

	    public string InvoiceAddressCityInKana {get;set;} 

	    public NoYes WillAutomaticInventoryReservationConsiderBatchAttributes {get;set;} 

	    public string IntrastatStatisticsProcedureCode {get;set;} 

	    public NoYes IsEInvoiceDimensionAccountCodeSpecifiedPerLine {get;set;} 

	    public NoYes OverrideSalesTax {get;set;} 

	    public string DeliveryAddressStreet {get;set;} 

	    public string DeliveryModeCode {get;set;} 

	    public NoYes IsExportSale {get;set;} 

	    [Required]
	    public DateTimeOffset ConfirmedShippingDate {get;set;} // not null

	    [Required]
	    public DateTimeOffset FixedDueDate {get;set;} // not null

	    [Required]
	    public Guid TransportationDocumentLineId {get;set;} // not null

	    public string SalesTaxGroupCode {get;set;} 

	    public NoYes IsDeliveryAddressOrderSpecific {get;set;} 

	    public string CustomerRequisitionNumber {get;set;} 

	    [Required]
	    public decimal InvoiceAddressLongitude {get;set;} // not null

	    public string InvoiceAddressCity {get;set;} 

	    public NoYes IsFinalUser {get;set;} 

	    public string InvoiceAddressPostBox {get;set;} 

	    public string ShippingCarrierServiceGroupId {get;set;} 

	    public string ContactPersonId {get;set;} 

	    public Listcode EUSalesListCode {get;set;} 

	    public string InvoiceAddressDistrictName {get;set;} 

	    public NoYes ThirdPartySalesDigitalPlatform {get;set;} 

	    public string PaymentTermsName {get;set;} 

	    public string DeliveryAddressCityInKana {get;set;} 

	    [Required]
	    public DateTimeOffset BaseDocumentDate {get;set;} // not null

	    public string CustomerPostingProfileId {get;set;} 

	    [Required]
	    public decimal DeliveryAddressLongitude {get;set;} // not null

	    public string TenderCode {get;set;} 

	    public string InvoiceAddressZipCode {get;set;} 

	    public string DeliveryTermsCode {get;set;} 

	    public string ShippingCarrierServiceId {get;set;} 

	    public string DefaultLedgerDimensionDisplayValue {get;set;} 

	    public Timezone DeliveryAddressTimeZone {get;set;} 

	    public string SalesOrderName {get;set;} 

	    public string DefaultShippingWarehouseId {get;set;} 

	    public NoYes IsEntryCertificateRequired {get;set;} 

	    public string DeliveryAddressStateId {get;set;} 

	    public string DeliveryBuildingCompliment {get;set;} 

	    public string IntrastatTransportModeCode {get;set;} 

	    public PaymentStub InvoicePaymentAttachmentType {get;set;} 

	    public string DeliveryAddressPostBox {get;set;} 

	    public Timezone InvoiceAddressTimeZone {get;set;} 

	    public string InvoiceAddressCountyId {get;set;} 

	    public string DirectDebitMandateId {get;set;} 

	    public string LineDiscountCustomerGroupCode {get;set;} 

	    public string IntrastatPortId {get;set;} 

	    public string CIPEcode {get;set;} 

	    public string OrderingCustomerAccountNumber {get;set;} 

	    public string CustomerPaymentFineCode {get;set;} 

	    public string InvoiceBuildingCompliment {get;set;} 

	    public string PriceCustomerGroupCode {get;set;} 

	    public string DeliveryReasonCode {get;set;} 

	    public NoYes IsServiceDeliveryAddressBased {get;set;} 

	    [Required]
	    public decimal ReportingCurrencyFixedExchangeRate {get;set;} // not null

	    [Required]
	    public decimal OrderHeaderTaxAmount {get;set;} // not null

	    public ItemReservation InventoryReservationMethod {get;set;} 

	    [Required]
	    public DateTimeOffset RequestedShippingDate {get;set;} // not null

	    public SalesOrderProcessingStatus SalesOrderProcessingStatus {get;set;} 

	    public string TransportationRoutePlanId {get;set;} 

	    public NoYes SkipCreateAutoCharges {get;set;} 

	    public string CustomerPaymentMethodName {get;set;} 

	    public string SalesUnitId {get;set;} 

	    [Required]
	    public decimal FixedExchangeRate {get;set;} // not null

	    public string ENCPromotionTypeId {get;set;} 

	    public string RevRecReallocationId {get;set;} 

	    public NoYes RevRecFollowOriginalPricingMethod {get;set;} 

	    public NoYes RevRecMultipleSOReallocation {get;set;} 

	    [Required]
	    public DateTimeOffset RevRecContractEndDate {get;set;} // not null

	    [Required]
	    public long RevRecLatestReverseJournal {get;set;} // not null

	    [Required]
	    public DateTimeOffset RevRecContractStartDate {get;set;} // not null

	    public NoYes FBEEOSSubmitted {get;set;} 

	    [Required]
	    public int FBEEOSReferenceId {get;set;} // not null

	    [Required]
	    public int FBEShopifyOrderNumber {get;set;} // not null

	    public NoYes FBEDropShip {get;set;} 

	    public string FBEKiboId {get;set;} 

	    [Required]
	    public long OrderHeaderRecId {get;set;} // not null

	    [Required]
	    public int FBEEOSOrderTypeId {get;set;} // not null

	    [Required]
	    public int FBEKiboReturnNumber {get;set;} // not null

	    [Required]
	    public DateTimeOffset Deadline {get;set;} // not null

	    [Required]
	    public long FBEShopifyId {get;set;} // not null

	}

	public partial class FBEJmgJob
	{
	    [Key]
	    [Required]
	    public string dataAreaId {get;set;} //PrimaryKey not null

	    [Key]
	    [Required]
	    public string JobId {get;set;} //PrimaryKey not null

	    public string ItemId {get;set;} 

	    public string Description {get;set;} 

	    [Required]
	    public int FromTime {get;set;} // not null

	    [Required]
	    public DateTimeOffset ToDate {get;set;} // not null

	    public string ModuleRefId {get;set;} 

	    [Required]
	    public decimal CalcQty {get;set;} // not null

	    [Required]
	    public int ToTime {get;set;} // not null

	    public string OprActId {get;set;} 

	    public NoYes Locked {get;set;} 

	    public NoYes ReportedFinished {get;set;} 

	    public string WrkCtrId {get;set;} 

	    [Required]
	    public DateTimeOffset FromDate {get;set;} // not null

	    public JmgJobTableType Type {get;set;} 

	    public RouteOprPriority Priority {get;set;} 

	    [Required]
	    public decimal PdsCWCalcQty {get;set;} // not null

	    public string InventSiteId {get;set;} 

	    [Required]
	    public int OprNum {get;set;} // not null

	    public string OriginalResource {get;set;} 

	    public string Sku {get;set;} 

	    [Required]
	    public long ResourceGroup {get;set;} // not null

	    [Required]
	    public int PriorityResource {get;set;} // not null

	}

	public partial class FBEProductionJournal
	{
	    [Key]
	    [Required]
	    public string dataAreaId {get;set;} //PrimaryKey not null

	    [Key]
	    [Required]
	    public string JournalId {get;set;} //PrimaryKey not null

	    [Required]
	    public decimal PdsCWBatchErr {get;set;} // not null

	    [Required]
	    public int OprNum {get;set;} // not null

	    [Required]
	    public DateTimeOffset PostedDateTime {get;set;} // not null

	    public NoYes InventControlProposal {get;set;} 

	    [Required]
	    public int NumOfLines {get;set;} // not null

	    public string ProdId {get;set;} 

	    public NoYes ProdAutoPickList {get;set;} 

	    [Required]
	    public decimal qtyGood {get;set;} // not null

	    public NoYes AutoReportFinished {get;set;} 

	    public NoYes EndJob {get;set;} 

	    public ProdJournalType JournalType {get;set;} 

	    public string Description {get;set;} 

	    public NoYes WaitCreateLine {get;set;} 

	    [Required]
	    public DateTimeOffset SessionLoginDateTime {get;set;} // not null

	    [Required]
	    public int SessionId {get;set;} // not null

	    public string JournalNameIdReportFinish {get;set;} 

	    public NoYes SystemBlocked {get;set;} 

	    public string BlockUserGroupId {get;set;} 

	    public string ProdRefJournalId_RU {get;set;} 

	    [Required]
	    public decimal qtyError {get;set;} // not null

	    public NoYes RouteAutoPickList {get;set;} 

	    public string BlockUserId {get;set;} 

	    public NoYes ReducePhysical {get;set;} 

	    public string JournalIdOriginal {get;set;} 

	    public ProdJournalType ProdRefJournalType_RU {get;set;} 

	    public ProdJournalVoucherChange VoucherChange {get;set;} 

	    public NoYes Posted {get;set;} 

	    public DetailSummary DetailSummary {get;set;} 

	    public string RefPurchId {get;set;} 

	    public string JournalNameIdPickList {get;set;} 

	    [Required]
	    public decimal PdsCWBatchGood {get;set;} // not null

	    public NoYes AcceptError {get;set;} 

	    public string JournalNameId {get;set;} 

	    public string RFUserId {get;set;} 

	    public NoYes DrawNegative {get;set;} 

	    public JournalVoucherDraw VoucherDraw {get;set;} 

	    public NoYes DeletePostedLines {get;set;} 

	    public string PostedUserId {get;set;} 

	}

	public partial class PlannedOrder
	{
	    [Key]
	    [Required]
	    public string dataAreaId {get;set;} //PrimaryKey not null

	    [Key]
	    [Required]
	    public string RequirementPlanId {get;set;} //PrimaryKey not null

	    [Key]
	    [Required]
	    public string PlannedOrderNumber {get;set;} //PrimaryKey not null

	    public ReqPlanType RequirementPlanType {get;set;} 

	    public string BuyerGroupId {get;set;} 

	    public string ProductSearchName {get;set;} 

	    public NoYes IsLeadTimeUsingWorkingDays {get;set;} 

	    [Required]
	    public int LeadTimeDays {get;set;} // not null

	    public string ProductConfigurationId {get;set;} 

	    public ReqPOStatus ProcessingStatus {get;set;} 

	    public string RequirementWarehouseLocationId {get;set;} 

	    public string AppendingPurchaseOrderNumber {get;set;} 

	    public string PurchaseUnitSymbol {get;set;} 

	    public string RequirementSiteId {get;set;} 

	    public string ProductDescription {get;set;} 

	    public string AppendingTransferOrderNumber {get;set;} 

	    public string ProductNumber {get;set;} 

	    public string ProductSizeId {get;set;} 

	    public string ItemNumber {get;set;} 

	    public string ProductVersionId {get;set;} 

	    public string RequirementPlanDescription {get;set;} 

	    [Required]
	    public DateTimeOffset DeliveryDate {get;set;} // not null

	    [Required]
	    public int OrderTime {get;set;} // not null

	    public SchedMethod SchedulingMethod {get;set;} 

	    [Required]
	    public DateTimeOffset ScheduledEndDate {get;set;} // not null

	    [Required]
	    public DateTimeOffset ScheduledStartDate {get;set;} // not null

	    public string ProductGroupId {get;set;} 

	    public ReqRefType PlannedOrderType {get;set;} 

	    [Required]
	    public decimal RequirementQuantity {get;set;} // not null

	    [Required]
	    public decimal CostAmount {get;set;} // not null

	    public string VendorGroupId {get;set;} 

	    public NoYes IsBulkOrder {get;set;} 

	    public string PlanningFormulaItemNumber {get;set;} 

	    [Required]
	    public DateTimeOffset PlannedOrderModifiedDateTime {get;set;} // not null

	    public string RequirementWarehouseId {get;set;} 

	    [Required]
	    public decimal RequirementCatchWeightQuantity {get;set;} // not null

	    [Required]
	    public decimal YieldPercentage {get;set;} // not null

	    [Required]
	    public int DeliveryTime {get;set;} // not null

	    public string VendorAccountNumber {get;set;} 

	    public string ProductColorId {get;set;} 

	    public NoYes IsDirectlyDerivedRequirement {get;set;} 

	    [Required]
	    public decimal PlanningPriority {get;set;} // not null

	    [Required]
	    public DateTimeOffset OrderDate {get;set;} // not null

	    public string BOMId {get;set;} 

	    [Required]
	    public decimal PurchaseQuantity {get;set;} // not null

	    public string PlannedOrderRouteOperationId {get;set;} 

	    [Required]
	    public bool IsSequencedPlannedBatchOrder {get;set;} // not null

	    [Required]
	    public DateTimeOffset RequirementDate {get;set;} // not null

	    public string ProductStyleId {get;set;} 

	    public NoYes RequirementPlanVersionActive {get;set;} 

	    [Required]
	    public int RequirementPlanVersion {get;set;} // not null

	}

	public partial class SalesOrderLine
	{
	    [Key]
	    [Required]
	    public string dataAreaId {get;set;} //PrimaryKey not null

	    [Key]
	    [Required]
	    public string InventoryLotId {get;set;} //PrimaryKey not null

	    [Required]
	    public DateTimeOffset RequestedReceiptDate {get;set;} // not null

	    [Required]
	    public decimal RetailCalculatedTotalDiscountPercentage {get;set;} // not null

	    public string EInvoiceDimensionAccountCode {get;set;} 

	    public string FormattedDelveryAddress {get;set;} 

	    public string ShippingWarehouseLocationId {get;set;} 

	    public SalesStatus SalesOrderLineStatus {get;set;} 

	    public string ProjectCategoryId {get;set;} 

	    public string ItemNumber {get;set;} 

	    public string DeliveryAddressDescription {get;set;} 

	    [Required]
	    public decimal MultilineDiscountPercentage {get;set;} // not null

	    public string ShippingWarehouseId {get;set;} 

	    public string GiftCardBuyerName {get;set;} 

	    public string GiftCardNumber {get;set;} 

	    public string CustomsDocumentNumber {get;set;} 

	    [Required]
	    public decimal LineDiscountAmount {get;set;} // not null

	    public string ProductStyleId {get;set;} 

	    public string ProductConfigurationId {get;set;} 

	    public string DeliverySalesTaxGroupCode {get;set;} 

	    public NoYes IsIntrastatTriangularDeal {get;set;} 

	    [Required]
	    public decimal MultilineDiscountAmount {get;set;} // not null

	    public string ItemBatchNumber {get;set;} 

	    public string DeliveryAddressCountryRegionId {get;set;} 

	    [Required]
	    public decimal DeliveryAddressLatitude {get;set;} // not null

	    public NoYes IsPriceLocked {get;set;} 

	    public string DeliveryAddressCity {get;set;} 

	    public string SalesProductCategoryName {get;set;} 

	    public SalesDeliveryDateControlType SalesOrderPromisingMethod {get;set;} 

	    public string ProjectId {get;set;} 

	    public string ProjectLinePropertyId {get;set;} 

	    public string DeliveryAddressDistrictName {get;set;} 

	    public string SalesRebateProductGroupId {get;set;} 

	    public string DeliveryAddressCountyId {get;set;} 

	    public string SalesUnitSymbol {get;set;} 

	    public string ItemWithholdingTaxCodeGroupCode {get;set;} 

	    [Required]
	    public DateTimeOffset ConfirmedReceiptDate {get;set;} // not null

	    public string ProductSizeId {get;set;} 

	    public string DeliveryAddressZipCode {get;set;} 

	    [Required]
	    public decimal FixedPriceCharges {get;set;} // not null

	    public string DeliveryAddressDunsNumber {get;set;} 

	    public string DeliveryTermsId {get;set;} 

	    public string ServiceFiscalInformationCode {get;set;} 

	    [Required]
	    public decimal RetailCalculatedTotalDiscountAmount {get;set;} // not null

	    public string DeliveryAddressName {get;set;} 

	    public string PackingUnitSymbol {get;set;} 

	    [Required]
	    public decimal OrderedSalesQuantity {get;set;} // not null

	    public string BOMId {get;set;} 

	    public string DeliveryAddressStreetNumber {get;set;} 

	    public string CreditNoteReasonCode {get;set;} 

	    public string DeliveryAddressStreetInKana {get;set;} 

	    public string ShippingSiteId {get;set;} 

	    [Required]
	    public long NGPCode {get;set;} // not null

	    [Required]
	    public decimal RetailCalculatedLineDiscountAmount {get;set;} // not null

	    public NoYes IsDeliveryAddressPrivate {get;set;} 

	    [Required]
	    public int LineCreationSequenceNumber {get;set;} // not null

	    [Required]
	    public decimal RetailCalculatedTenderDiscountPercentage {get;set;} // not null

	    public string MainAccountIdDisplayValue {get;set;} 

	    public string OrderedInventoryStatusId {get;set;} 

	    public string GiftCardRecipientEmail {get;set;} 

	    public string DeliveryAddressCountryRegionISOCode {get;set;} 

	    public string ItemSerialNumber {get;set;} 

	    [Required]
	    public decimal RetailCalculatedManualLineDiscountPercentage {get;set;} // not null

	    public NoYes CalculateLineAmount {get;set;} 

	    [Required]
	    public decimal RetailCalculatedPeriodicDiscountAmount {get;set;} // not null

	    public string IntrastatTransactionCode {get;set;} 

	    public string CurrencyCode {get;set;} 

	    public string DeliveryAddressLocationId {get;set;} 

	    public string SalesTaxItemGroupCode {get;set;} 

	    public string RouteId {get;set;} 

	    public string EInvoicePropertyNumber {get;set;} 

	    public string ProductVersionId {get;set;} 

	    public string CommissionSalesRepresentativeGroupId {get;set;} 

	    public string CustomsDocumentName {get;set;} 

	    public NoYes WillAutomaticInventoryReservationConsiderBatchAttributes {get;set;} 

	    public string IntrastatStatisticsProcedureCode {get;set;} 

	    public NoYes OverrideSalesTax {get;set;} 

	    public string LineDescription {get;set;} 

	    public string DeliveryAddressStreet {get;set;} 

	    public string DeliveryModeCode {get;set;} 

	    [Required]
	    public DateTimeOffset ConfirmedShippingDate {get;set;} // not null

	    [Required]
	    public decimal RetailCalculatedLineDiscountPercentage {get;set;} // not null

	    public string SalesTaxGroupCode {get;set;} 

	    public string ServiceOrderNumber {get;set;} 

	    public NoYes IsDeliveryAddressOrderSpecific {get;set;} 

	    public string CustomerRequisitionNumber {get;set;} 

	    public string SalesOrderNumber {get;set;} 

	    public string FiscalDocumentTypeId {get;set;} 

	    [Required]
	    public decimal PlanningPriority {get;set;} // not null

	    public string DeliveryCFOPCode {get;set;} 

	    [Required]
	    public decimal LineDiscountPercentage {get;set;} // not null

	    [Required]
	    public decimal SalesPrice {get;set;} // not null

	    public string GiftCardGiftMessage {get;set;} 

	    [Required]
	    public decimal OrderedCatchWeightQuantity {get;set;} // not null

	    [Required]
	    public decimal RetailCalculatedPeriodicDiscountPercentage {get;set;} // not null

	    public string OrderLineReference {get;set;} 

	    [Required]
	    public decimal AllowedUnderdeliveryPercentage {get;set;} // not null

	    public string DeliveryAddressCityInKana {get;set;} 

	    [Required]
	    public decimal AllowedOverdeliveryPercentage {get;set;} // not null

	    [Required]
	    public decimal DeliveryAddressLongitude {get;set;} // not null

	    public string IntrastatCommodityCode {get;set;} 

	    public string DefaultLedgerDimensionDisplayValue {get;set;} 

	    [Required]
	    public decimal LineNumber {get;set;} // not null

	    public Timezone DeliveryAddressTimeZone {get;set;} 

	    public string ProductColorId {get;set;} 

	    public string GiftCardRecipientName {get;set;} 

	    public string CFOPCode {get;set;} 

	    public string DeliverySalesTaxItemGroupCode {get;set;} 

	    public string DeliveryAddressStateId {get;set;} 

	    public string DeliveryBuildingCompliment {get;set;} 

	    public string IntrastatTransportModeCode {get;set;} 

	    public string DeliveryAddressPostBox {get;set;} 

	    [Required]
	    public DateTimeOffset CustomsDocumentDate {get;set;} // not null

	    [Required]
	    public int CustomersLineNumber {get;set;} // not null

	    public MCRGiftCardType GiftCardType {get;set;} 

	    [Required]
	    public decimal LineAmount {get;set;} // not null

	    public string IntrastatPortId {get;set;} 

	    public string IntrastatSpecialMovementCode {get;set;} 

	    [Required]
	    public decimal SalesPriceQuantity {get;set;} // not null

	    public NoYes WillRebateCalculationExcludeLine {get;set;} 

	    [Required]
	    public decimal RetailCalculatedTenderDiscountAmount {get;set;} // not null

	    [Required]
	    public decimal SuframaDiscountPercentage {get;set;} // not null

	    public ItemReservation InventoryReservationMethod {get;set;} 

	    [Required]
	    public DateTimeOffset RequestedShippingDate {get;set;} // not null

	    [Required]
	    public decimal RetailCalculatedManualLineDiscountAmount {get;set;} // not null

	    public string WithholdingTaxGroupCode {get;set;} 

	    public string FulfillmentStoreId {get;set;} 

	    public NoYes SkipCreateAutoCharges {get;set;} 

	    public string ExternalItemNumber {get;set;} 

	    [Required]
	    public decimal IntrastatStatisticValue {get;set;} // not null

	    public NoYes IsLineStopped {get;set;} 

	    public string GiftCardBuyerEmail {get;set;} 

	    public string RevRecRevenueScheduleId {get;set;} 

	    [Required]
	    public decimal RevRecSalesDeliverNow {get;set;} // not null

	    [Required]
	    public DateTimeOffset RevRecContractEndDate {get;set;} // not null

	    [Required]
	    public int RevRecOccurrences {get;set;} // not null

	    [Required]
	    public DateTimeOffset RevRecContractStartDate {get;set;} // not null

	    [Required]
	    public DateTimeOffset OriginalShipDate {get;set;} // not null

	    public string ProductionOrder {get;set;} 

	    public string RecordCreatedBy {get;set;} 

	    [Required]
	    public decimal DeliverSalesRemainder {get;set;} // not null

	    [Required]
	    public DateTimeOffset FBECustomerRequestDate {get;set;} // not null

	    [Required]
	    public DateTimeOffset RecordCreatedDateTime {get;set;} // not null

	    [Required]
	    public DateTimeOffset RecordModifiedDateTime {get;set;} // not null

	    public string smmCampaignId {get;set;} 

	    [Required]
	    public decimal DeliverRemainder {get;set;} // not null

	    public string RecordModifiedBy {get;set;} 

	    [Required]
	    public long FBEShopifyId {get;set;} // not null

	    public string FBEKiboId {get;set;} 

	    public string SourcingVendAccount {get;set;} 

	}

	public partial class FBEProductionOrderHeader
	{
	    [Key]
	    [Required]
	    public string dataAreaId {get;set;} //PrimaryKey not null

	    [Key]
	    [Required]
	    public string ProdId {get;set;} //PrimaryKey not null

	    public NoYes PmfTotalCostAllocation {get;set;} 

	    public ProdSchedStatus SchedStatus {get;set;} 

	    public string ProjTaxGroupId {get;set;} 

	    public SchedDirection LatestSchedDirection {get;set;} 

	    [Required]
	    public decimal PdsCWBatchStup {get;set;} // not null

	    [Required]
	    public DateTimeOffset SchedDate {get;set;} // not null

	    [Required]
	    public int GanttColorId {get;set;} // not null

	    [Required]
	    public DateTimeOffset BOMDate {get;set;} // not null

	    [Required]
	    public DateTimeOffset SchedEnd {get;set;} // not null

	    [Required]
	    public decimal PdsCWRemainInventPhysical {get;set;} // not null

	    [Required]
	    public decimal PdsCWBatchEst {get;set;} // not null

	    [Required]
	    public int LatestSchedTime {get;set;} // not null

	    public ProdPostingType ProdPostingType {get;set;} 

	    [Required]
	    public int SchedToTime {get;set;} // not null

	    public NoYes PmfBulkOrd {get;set;} 

	    public string InventRefId {get;set;} 

	    public NoYes RouteJobs {get;set;} 

	    public ProdWHSReleasePolicy ProdWHSReleasePolicy {get;set;} 

	    public string ReqPOId {get;set;} 

	    public string InventRefTransId {get;set;} 

	    [Required]
	    public decimal ProjCostAmount {get;set;} // not null

	    public string InventTransId {get;set;} 

	    public string InventDimId {get;set;} 

	    public string ProdOrigId {get;set;} 

	    public ProjProdPostingType ProjPostingType {get;set;} 

	    [Required]
	    public decimal QtyCalc {get;set;} // not null

	    [Required]
	    public DateTimeOffset LatestSchedDate {get;set;} // not null

	    [Required]
	    public int DlvTime {get;set;} // not null

	    [Required]
	    public decimal Height {get;set;} // not null

	    public string BOMId {get;set;} 

	    [Required]
	    public int SchedFromTime {get;set;} // not null

	    public string CollectRefProdId {get;set;} 

	    [Required]
	    public decimal Depth {get;set;} // not null

	    [Required]
	    public decimal PdsCWBatchSched {get;set;} // not null

	    [Required]
	    public decimal ProjCostPrice {get;set;} // not null

	    [Required]
	    public decimal Width {get;set;} // not null

	    public string ProjSalesCurrencyId {get;set;} 

	    [Required]
	    public DateTimeOffset StUpDate {get;set;} // not null

	    public NoYes ProdLocked {get;set;} 

	    [Required]
	    public DateTimeOffset DlvDate {get;set;} // not null

	    [Required]
	    public decimal ProjSalesPrice {get;set;} // not null

	    public string ProdGroupId {get;set;} 

	    public NoYes SkipCreateRouteOperations {get;set;} 

	    public string ProdPoolId {get;set;} 

	    public ProdType ProdType {get;set;} 

	    public string RouteId {get;set;} 

	    [Required]
	    public int ProdPrio {get;set;} // not null

	    public string PmfConsOrdId {get;set;} 

	    [Required]
	    public DateTimeOffset SchedStart {get;set;} // not null

	    public NoYes SkipCreateBOMLines {get;set;} 

	    public string CurrencyCode_RU {get;set;} 

	    public byte[] PackedExtensions {get;set;} 

	    public string Name {get;set;} 

	    public ProdStatus ProdStatus {get;set;} 

	    public string ProjTransId {get;set;} 

	    public string ItemId {get;set;} 

	    public string RecordCreatedBy {get;set;} 

	    public string ProjTaxItemGroupId {get;set;} 

	    [Required]
	    public decimal QtySched {get;set;} // not null

	    public string ReqPlanIdSched {get;set;} 

	    [Required]
	    public decimal PmfYieldPct {get;set;} // not null

	    public string DefaultDimensionDisplayValue {get;set;} 

	    [Required]
	    public DateTimeOffset RealDate {get;set;} // not null

	    public NoYes ProjLinkedToOrder {get;set;} 

	    public NoYes CheckRoute {get;set;} 

	    public string ProjSalesUnitId {get;set;} 

	    public string ActivityNumber {get;set;} 

	    public NoYes PmfCoByVarAllow {get;set;} 

	    public string PriceGroup_RU {get;set;} 

	    public CostProfitSet ProfitSet {get;set;} 

	    public string PropertyId {get;set;} 

	    public ProdRefLookUp RefLookUp {get;set;} 

	    [Required]
	    public decimal RemainInventPhysical {get;set;} // not null

	    public InventRefType InventRefType {get;set;} 

	    [Required]
	    public DateTimeOffset FinishedDate {get;set;} // not null

	    [Required]
	    public DateTimeOffset ReleasedDate {get;set;} // not null

	    public ProdBackStatus BackorderStatus {get;set;} 

	    [Required]
	    public decimal PdsCWBatchSize {get;set;} // not null

	    [Required]
	    public int CollectRefLevel {get;set;} // not null

	    public NoYes PmfReworkBatch {get;set;} 

	    public string ProjCategoryId {get;set;} 

	    public string ProjLinePropertyId {get;set;} 

	    [Required]
	    public DateTimeOffset RecordCreatedDateTime {get;set;} // not null

	    [Required]
	    public decimal QtyStUp {get;set;} // not null

	    [Required]
	    public DateTimeOffset CalcDate {get;set;} // not null

	    [Required]
	    public decimal Density {get;set;} // not null

	    public ProdReservation Reservation {get;set;} 

	    public string ProjId {get;set;} 

	}

	public partial class ProductionOrderBillOfMaterialLine
	{
	    [Key]
	    [Required]
	    public string dataAreaId {get;set;} //PrimaryKey not null

	    [Key]
	    [Required]
	    public string ProductionOrderNumber {get;set;} //PrimaryKey not null

	    [Key]
	    [Required]
	    public decimal LineNumber {get;set;} //PrimaryKey not null

	    [Required]
	    public decimal BOMLineQuantity {get;set;} // not null

	    public string ProductStyleId {get;set;} 

	    public string SubcontractingPurchaseOrderNumber {get;set;} 

	    public NoYes IsFullyConsumed {get;set;} 

	    public ProdReservation AutoReservationMode {get;set;} 

	    public string DemandProductionOrderLineInventoryLotId {get;set;} 

	    public string DemandProductionOrderNumber {get;set;} 

	    public string InventoryStatusId {get;set;} 

	    public string ItemNumber {get;set;} 

	    [Required]
	    public decimal PhysicalProductDensity {get;set;} // not null

	    public ProdFlushingPrincipBOM FlushingPrinciple {get;set;} 

	    [Required]
	    public decimal VariableScrapPercentage {get;set;} // not null

	    public string SubRouteOperationId {get;set;} 

	    [Required]
	    public decimal PhysicalProductHeight {get;set;} // not null

	    [Required]
	    public decimal ReleasedBOMLineQuantity {get;set;} // not null

	    [Required]
	    public decimal BOMLineQuantityDenominator {get;set;} // not null

	    [Required]
	    public decimal RemainingBOMLineQuantity {get;set;} // not null

	    public NoYes IsConsumedAtOperationComplete {get;set;} 

	    public string DefaultDimensionDisplayValue {get;set;} 

	    public NoYes IsConstantConsumptionReleased {get;set;} 

	    public string DemandTransferOrderNumber {get;set;} 

	    public string ProductSizeId {get;set;} 

	    [Required]
	    public decimal RemainingInventoryQuantity {get;set;} // not null

	    public string DemandSalesOrderNumber {get;set;} 

	    [Required]
	    public decimal StartedInventoryQuantity {get;set;} // not null

	    public string DemandProductionOrderLineNumber {get;set;} 

	    [Required]
	    public decimal PhysicalProductDepth {get;set;} // not null

	    public BOMRoundUp RoundingUpMethod {get;set;} 

	    public string SubcontractingPurchaseOrderLineInventoryLotId {get;set;} 

	    public string DemandProductionOrderHeaderInventoryLotId {get;set;} 

	    [Required]
	    public int RouteOperationNumber {get;set;} // not null

	    [Required]
	    public decimal ConsumptionCalculationConstant {get;set;} // not null

	    public string ConsumptionWarehouseId {get;set;} 

	    public string PositionNumber {get;set;} 

	    public string DemandInventoryJournalLineInventoryLotId {get;set;} 

	    [Required]
	    public decimal RoundingUpMultiplesBOMLineQuantity {get;set;} // not null

	    public string InventoryLotId {get;set;} 

	    public NoYes WillCostCalculationIncludeLine {get;set;} 

	    [Required]
	    public int RawMaterialScheduledConsumptionTime {get;set;} // not null

	    public BOMType LineType {get;set;} 

	    [Required]
	    public decimal EstimatedBOMLineQuantity {get;set;} // not null

	    [Required]
	    public decimal StartedBOMLineQuantity {get;set;} // not null

	    public string SourcePlannedOrderNumber {get;set;} 

	    public string ProductConfigurationId {get;set;} 

	    public string DemandTransferOrderLineReceivingInventoryLotId {get;set;} 

	    [Required]
	    public bool IsResourceConsumptionUsed {get;set;} // not null

	    public string ProductVersionId {get;set;} 

	    [Required]
	    public DateTimeOffset RawMaterialScheduledConsumptionDate {get;set;} // not null

	    public ProdBackStatus LineRemainderStatus {get;set;} 

	    public string SourceBOMId {get;set;} 

	    public string ConsumptionSiteId {get;set;} 

	    public string DemandSalesOrderLineInventoryLotId {get;set;} 

	    public string SourceMasterPlanId {get;set;} 

	    [Required]
	    public decimal EstimatedInventoryQuantity {get;set;} // not null

	    public string ItemBatchNumber {get;set;} 

	    public string SubBOMId {get;set;} 

	    public string ProductColorId {get;set;} 

	    [Required]
	    public decimal PhysicalProductWidth {get;set;} // not null

	    public BOMConsumpType ConsumptionType {get;set;} 

	    public string ConsumptionWarehouseLocationId {get;set;} 

	    public BOMFormula ConsumptionCalculationMethod {get;set;} 

	    [Required]
	    public decimal ConstantScrapBOMLineQuantity {get;set;} // not null

	    public string SubcontractingVendorAccountNumber {get;set;} 

	    public string DemandInventoryJournalNumber {get;set;} 

	    public string InventoryOwnerId {get;set;} 

	    public string BOMLineUnitSymbol {get;set;} 

	}

	public partial class DimensionSet
	{
	    [Key]
	    [Required]
	    public long RecordId {get;set;} //PrimaryKey not null

	    public string DisplayValue {get;set;} 

	    public string MainAccount {get;set;} 

	}

	public enum NoYes
	 {
 		No=0,
		Yes=1 
	}
	public enum TableGroupAll
	 {
 		Table=0,
		GroupId=1,
		All=2 
	}
	public enum RouteOprPriority
	 {
 		Primary=0,
		Secondary1=1,
		Secondary2=2,
		Secondary3=3,
		Secondary4=4,
		Secondary5=5,
		Secondary6=6,
		Secondary7=7,
		Secondary8=8,
		Secondary9=9,
		Secondary10=10,
		Secondary11=11,
		Secondary12=12,
		Secondary13=13,
		Secondary14=14,
		Secondary15=15,
		Secondary16=16,
		Secondary17=17,
		Secondary18=18,
		Secondary19=19,
		Secondary20=20 
	}
	public enum RouteJobType
	 {
 		QueueBefore=0,
		Setup=1,
		Process=2,
		Overlap=3,
		Transport=4,
		QueueAfter=5,
		Burden=6 
	}
	public enum ProdErrorCause
	 {
 		None=0,
		Material=1,
		Machine=2,
		OperatingStaff=3,
		BadComponent=4,
		BlankAlignment=5,
		BlemishOnBlank=6,
		SplitFerrule=7,
		Dimple=8,
		Bubbles=9,
		DryThread=10,
		ExcessCoating=11,
		FerruleFit=12,
		FoamyBubbles=13,
		GuideNotAligned=14,
		LintCoating=15,
		Lumpy=16,
		RodMisc=17,
		MissingTrimWrap=18,
		Pokies=19,
		PullBack=20,
		LostWIP=21,
		ScratchBlank=22,
		SerialIllegible=23,
		SSDefect=24,
		Soot=25,
		TackyCoating=26,
		Tails=27,
		TouchMark=28,
		WcNotFlush=29,
		BrokenMisc=30,
		BrokenTest=31,
		CelloDefect=32,
		ClearDefect=33,
		ColorDefect=34,
		Contamination=35,
		BlankMisc=36,
		PatternDefect=37,
		ResandIssue=38,
		SandingDefect=39,
		TackDefect=40,
		WaterSpots=41,
		WhiteDots=42,
		MandrelError=43,
		WARBlemish=44,
		WARBroken=45,
		WARCrooked=46,
		WARCut=47,
		WARGuide=48,
		WARNick=49,
		WARSub=50,
		CustReturn=51,
		OverReport=52,
		PeaksInLine=53,
		BubblesInLine=54,
		DivotsBumps=55,
		OffCenter=56,
		PrintingDefect=57,
		Bleeding=58,
		SurfaceRoughness=59,
		CoilerScrap=60,
		PreppingScrap=61,
		WeldingScrap=62,
		Debris=63,
		MechanicalFailure=64,
		OperatorIntentionalFlaw=65,
		Transitions=66,
		Other=67 
	}
	public enum Timezone
	 {
 		GMTMINUS1200INTERNATIONALDATELINEWEST=24,
		GMTMINUS1100COORDINATEDUNIVERSALTIME=99,
		GMTMINUS1100MIDWAYISLAND_SAMOA=65,
		GMTMINUS1000HAWAII=39,
		GMTMINUS0900ALASKA=2,
		GMTMINUS0800PACIFICTIME=58,
		GMTMINUS0800TIJUANA_BAJACALIFORNIA=59,
		GMTMINUS0700ARIZONA=75,
		GMTMINUS0700MOUNTAINTIME=47,
		GMTMINUS0700CHIHUAHUA_LAPAZ_MAZATLAN=48,
		GMTMINUS0600CENTRALAMERICA=15,
		GMTMINUS0600CENTRALTIME=21,
		GMTMINUS0600GUADALAJARA_MEXICOCITY=22,
		GMTMINUS0600SASKATCHEWAN=11,
		GMTMINUS0500BOGOTA_LIMA_QUITO_RIOBRANCO=63,
		GMTMINUS0500EASTERNTIME=29,
		GMTMINUS0500INDIANA=74,
		GMTMINUS0500CHETUMAL=255,
		GMTMINUS0400ASUNCION=95,
		GMTMINUS0400ATLANTICTIME=6,
		GMTMINUS0400LAPAZ=64,
		GMTMINUS0400MANAUS=17,
		GMTMINUS0300SANTIAGO=57,
		GMTMINUS0430CARACAS=85,
		GMTMINUS0330NEWFOUNDLAND=54,
		GMTMINUS0300_SALVADOR=87,
		GMTMINUS0300BRASILIA=28,
		GMTMINUS0300BUENOSAIRES=86,
		GMTMINUS0300BUENOSAIRES_GEORGETOWN=62,
		GMTMINUS0300GREENLAND=36,
		GMTMINUS0300MONTEVIDEO=83,
		GMTMINUS0200MIDATLANTIC=45,
		GMTMINUS0100AZORES=10,
		GMTMINUS0100CAPEVERDIS=12,
		GMT_CASABLANCA=93,
		GMT_CASABLANCA_MONTROVIA_REYKJAVIK=37,
		GMT_COORDINATEDUNIVERSALTIME=89,
		GMT_DUBLIN_EDINBURGH_LISBON_LONDON=35,
		GMT_PLUS0300KALININGRAD_MINSK=90,
		GMTPLUS0100_AMSTERDAM_BERLIN_BERN_ROME=79,
		GMTPLUS0100BELGRADE_BRATISLAVA_BUDAPEST=18,
		GMTPLUS0100BRUSSELS_COPENHAGEN_MADRID=60,
		GMTPLUS0100SARAJEVO_SKOPJE_WARSAW_ZAGREB=19,
		GMTPLUS0100TRIPOLI=101,
		GMTPLUS0100WESTCENTRALAFRICA=78,
		GMTPLUS0200_DAMASCUS=96,
		GMTPLUS0200AMMAN=43,
		GMTPLUS0200ATHENS_BUCHAREST_ISTANBUL=38,
		GMTPLUS0200BEIRUT=46,
		GMTPLUS0200MINSK=27,
		GMTPLUS0200CAIRO=30,
		GMTPLUS0200HARARE_PRETORIA=68,
		GMTPLUS0200HELSINKI_KYIV_RIGA_VILNIUS=33,
		GMTPLUS0300ISTANBUL=98,
		GMTPLUS0200JERUSALEM=42,
		GMTPLUS0200WINDHOEK=51,
		GMTPLUS0300BAGHDAD=5,
		GMTPLUS0300KUWAIT_RIYADH=3,
		GMTPLUS0300MOSCOW_STPETERSBURG_VOLGOGRAD=61,
		GMTPLUS0300NAIROBI=25,
		GMTPLUS0300TBILISI=34,
		GMTPLUS0330TEHRAN=41,
		GMTPLUS0400ABUDHABI_MUSCAT=4,
		GMTPLUS0400BAKU=9,
		GMTPLUS0400IZHEVSK_SAMARA=104,
		GMTPLUS0400CAUCASUSSTANDARDTIME=84,
		GMTPLUS0400PORTLOUIS=92,
		GMTPLUS0400YEREVAN=13,
		GMTPLUS0430KABUL=1,
		GMTPLUS0500EKATERINBURG=31,
		GMTPLUS0500ISLAMABAD_KARACHI=94,
		GMTPLUS0500ISLAMABAD_KARACHI_TASHKENT=255,
		GMTPLUS0530CHENNAI_KOLKATA_MUMBAI=40,
		GMTPLUS0530SRIJAYAWARDENEPURA=69,
		GMTPLUS0545KATHMANDU=52,
		GMTPLUS0600ALMATY_NOVOSIBIRSK=50,
		GMTPLUS0600ASTANA_DHAKA=16,
		GMTPLUS0600DHAKA=88,
		GMTPLUS0600MAGADAN=91,
		GMTPLUS0630_YANGON=49,
		GMTPLUS0700_BANGKOK_HANOI_JAKARTA=66,
		GMTPLUS0700KRASNOYARSK=56,
		GMTPLUS0800_ULAANBAATAR=97,
		GMTPLUS0800BEIJING_CHONGQING_HONGKONG=23,
		GMTPLUS0800IRKUTSK_ULAANBATAAR=55,
		GMTPLUS0800KUALALUMPUR_SINGAPORE=67,
		GMTPLUS0800PERTH=77,
		GMTPLUS0800TAIPEI=70,
		GMTPLUS0900OSAKA_SAPPORO_TOKYO=72,
		GMTPLUS0900SEOUL=44,
		GMTPLUS0900YAKUTSK=82,
		GMTPLUS0930ADELAIDE=14,
		GMTPLUS0930DARWIN=7,
		GMTPLUS1000BRISBANE=26,
		GMTPLUS1000CANBERRA_MELBOURNE_SYDNEY=8,
		GMTPLUS1000GUAM_PORTMORESBY=81,
		GMTPLUS1000HOBART=71,
		GMTPLUS1000VLADIVOSTOK=76,
		GMTPLUS1100CHOKURDAKH=102,
		GMTPLUS1100MAGADAN_SOLOMONIS=20,
		GMTPLUS1200ANADYR_PETRO_KAMCHATSKY=103,
		GMTPLUS1200AUCKLAND_WELLINGTON=53,
		GMTPLUS1200COORDINATEDUNIVERSALTIME=100,
		GMTPLUS1200FIJI_KAMCHATKA_MARSHALLIS=32,
		GMTPLUS1300NUKU_ALOFA=73 
	}
	public enum BOMFormula
	 {
 		Formula0=0,
		Formula1=1,
		Formula2=2,
		Formula3=3,
		Formula4=4,
		Formula5=5 
	}
	public enum BOMType
	 {
 		Item=0,
		Phantom=1,
		PeggedSupply=2,
		Vendor=3 
	}
	public enum BOMRoundUp
	 {
 		No=0,
		Qty=1,
		MeasureConfig=2,
		Consumption=3 
	}
	public enum BOMConsumpType
	 {
 		Variable=0,
		Constant=1 
	}
	public enum ProdFlushingPrincipBOM
	 {
 		Blank=0,
		Start=2,
		Finish=3,
		Manual=1,
		Picked=4 
	}
	public enum ProdBackStatus
	 {
 		None=0,
		Release=1,
		Route=2,
		Receipt=3,
		Completed=5 
	}
	public enum NoYesCombo
	 {
 		No=0,
		Yes=1 
	}
	public enum InventRefType
	 {
 		None=0,
		Sales=1,
		Purch=2,
		Production=3,
		ProdLine=4,
		InventJournal=5,
		CRMQuotation=6,
		InventTransfer=7,
		FixedAsset=8 
	}
	public enum SchedJobLinkType
	 {
 		None=0,
		Soft=1,
		Hard=2 
	}
	public enum EFDocPresenceType_BR
	 {
 		DoesNotApply=0,
		InPerson=1,
		Internet=2,
		Telesales=3,
		InPersonOut=5,
		Others=9 
	}
	public enum PaymentStub
	 {
 		None=0,
		FIK=1,
		BBS=2,
		ESR_blue_PTT=3,
		ESR_red_bank=4,
		FIK762=5,
		ESR_orange=6,
		BelSMS101=7,
		BelSMS102=8,
		Finnish=9,
		FIK751=10,
		FIK752=11,
		QRBill=12 
	}
	public enum SalesDeliveryDateControlType
	 {
 		None=0,
		SalesLeadTime=1,
		ATP=2,
		ATPPlusIssueMargin=3,
		CTP=4 
	}
	public enum ItemReservation
	 {
 		None=0,
		Automatic=1,
		Explosion=2 
	}
	public enum DetailSummary
	 {
 		Detail=0,
		Summary=1 
	}
	public enum JournalVoucherDraw
	 {
 		Entering=0,
		Post=1 
	}
	public enum RouteOprType
	 {
 		Standard=0,
		Vendor=1 
	}
	public enum JmgJobPayTypeEnum
	 {
 		Empty=0,
		Hours=1,
		PieceRate=2 
	}
	public enum Listcode
	 {
 		IncludeNot=0,
		EUTrade=1,
		ProductionOnToll=2,
		TriangularEUTrade=3,
		TriangularProductionOnToll=4,
		PropertyMoving_CZ=50,
		TriangularIntermediateRole_HU=51,
		DEL_EUService=52,
		PurchasedOnBehalf_LV=53 
	}
	public enum ProdStatus
	 {
 		Created=0,
		CostEstimated=1,
		Scheduled=2,
		Released=3,
		StartedUp=4,
		ReportedFinished=5,
		Completed=7 
	}
	public enum SettlementType
	 {
 		None=0,
		OpenTransact=1,
		SelectedTransact=2 
	}
	public enum DocumentType_IT
	 {
 		None=0,
		PaymentOrder=1,
		Contract=2,
		Agreement=3,
		ManagementSystem=4,
		OriginalInvoice=5 
	}
	public enum SalesStatus
	 {
 		None=0,
		Backorder=1,
		Delivered=2,
		Invoiced=3,
		Canceled=4 
	}
	public enum InvoiceType_MY
	 {
 		Invoice=0,
		GST=1,
		SelfBilled=2,
		ServiceInvoice=3 
	}
	public enum SalesOrderProcessingStatus
	 {
 		Active=0,
		Confirmed=1,
		Picked=2,
		PartiallyDelivered=3,
		Delivered=4,
		Invoiced=5,
		PartiallyInvoiced=6,
		Canceled=7 
	}
	public enum RouteFormula
	 {
 		Formula0=0,
		Formula1=1,
		Formula2=2,
		Formula3=3 
	}
	public enum JmgJobTableType
	 {
 		ProdQueueBefore=0,
		ProdSetup=1,
		ProdProcess=2,
		ProdOverlap=3,
		ProdTransport=4,
		ProdQueueAfter=5,
		ProjProject=6,
		ProjActivity=7,
		ProjBudget=8,
		SFCActivity=9,
		HRMAbsenceCodeGroup=10,
		HRMAbsenceCode=11,
		SFCClockIn=12,
		SFCClockOut=13,
		SFCBreak=14,
		SFCStartTeam=15,
		SFCStopTeam=16,
		SFCEventCode=17,
		SFCOnCall=18 
	}
	public enum ProdReservation
	 {
 		None=0,
		Estimation=1,
		Scheduling=2,
		Start=3,
		Release=4 
	}
	public enum ProdSchedStatus
	 {
 		None=0,
		OperationScheduled=1,
		JobScheduled=2 
	}
	public enum ProdPostingType
	 {
 		ItemWrkCtr=0,
		ItemCategory=1,
		ProdGroup=2 
	}
	public enum CostProfitSet
	 {
 		Standard=0,
		Profit1=1,
		Profit2=2,
		Profit3=3 
	}
	public enum SchedDirection
	 {
 		None=0,
		Forward=1,
		Backward=2 
	}
	public enum ProdWHSReleasePolicy
	 {
 		AllowPartialReservation=0,
		RequireFullReservation=1 
	}
	public enum MCRGiftCardType
	 {
 		Email=0,
		Physical=1 
	}
	public enum RouteAll
	 {
 		Route=0,
		All=1 
	}
	public enum ProdJournalType
	 {
 		Picklist=0,
		ReportFinished=1,
		RouteCard=2,
		JobCard=3,
		DEL_PmfCoByProduct=4,
		ReleaseFromProduction_RU=100 
	}
	public enum ProdJournalVoucherChange
	 {
 		DateProdChange=0 
	}
	public enum ReqPlanType
	 {
 		SchedPlan=0,
		ForecastPlan=1,
		MCRContPlan=250 
	}
	public enum ReqPOStatus
	 {
 		Unadministered=0,
		Administered=1,
		Approved=2 
	}
	public enum SchedMethod
	 {
 		Rough=0,
		Detail=1 
	}
	public enum ReqRefType
	 {
 		None=0,
		InventOnHand=1,
		Purch=8,
		Production=9,
		Sales=10,
		ProdLine=12,
		InventJournal=13,
		SafetyInvent=14,
		InventTransfer=15,
		TransferOrderShip=16,
		TransferOrderReceive=17,
		SalesForecast=21,
		BOMPlannedOrder=31,
		BOMLine=32,
		ItemPlannedOrder=33,
		TransferPlannedOrder=34,
		TransferDemand=35,
		DEL_smmQuotation=36,
		Quarantine=37,
		SalesQuotation=38,
		Kanban=39,
		KanbanLine=40,
		PlannedKanban=41,
		PlannedKanbanLine=42,
		PmfFormulaLine=45,
		PmfPlannedProdBatch=46,
		PdsExpiredBatch=47,
		PmfCoProduct=49,
		PlannedIntercompanyDemand=43,
		Statement=101,
		RequisitionLine=50,
		MCRContinuity=250,
		ConsignmentReplenishmentOrder=51 
	}
	public enum JmgTermRegType
	 {
 		ClockIn=0,
		JobStop=1,
		JobStart=2,
		TeamStop=3,
		TeamStart=4,
		BrkFlowStart=5,
		BrkCancelOne=6,
		BrkCancelAll=7,
		BrkFlowStop=8,
		FinishQty=9,
		ClockOut=10,
		EventCode=11 
	}
	public enum ProjProdPostingType
	 {
 		None=0,
		DEL_LinkedToOrder=1,
		FinishedItemMethod=2,
		ConsumedMethod=3 
	}
	public enum ProdType
	 {
 		Standard=0,
		Vendor=3,
		Process=4 
	}
	public enum ProdRefLookUp
	 {
 		Production=0,
		Sales=1 
	}
}
